### ISSUE TITLE
@wetling23 getting error which running threshold report

### ISSUE THREAD

**Issue by Dharmbodh** [wetling23/Public.LogicMonitorPsScripts#1]
getting below error which running threshold report. can you please help to solve this.

.\ThresholdReport-Script.ps1 -AccessId ziduuG342acN6RAjWj7C -AccessKey 'lma_3cL9u7EMwL2joHvi' -AccountName sandbox -GroupId 2011
C:\Downloads\ThresholdReport-Script.ps1 : Cannot process argument transformation on parameter 
'AccessKey'. Cannot convert the 
"lma_3cL9u7EMwL2joHvi" 
value of type "System.String" to type "System.Security.SecureString".
At line:1 char:72
+ ...  -AccessKey 'lma_3cL9u7EMwL2joHvi
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ThresholdReport-Script.ps1], ParameterBindingArgumentTransformationExceptio 
   n
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,ThresholdReport-Script.ps1

**Comment by Dharmbodh** [comment]
@wetling23  can you please check

**Comment by wetling23** [comment]
@Dharmbodh you need to send a secure string to the -AccessKey parameter, not a regular string. 

```
PS C:\> $accesskey = 'lma_3cL9u7EMwL2joHvi...' | ConvertTo-SecureString -AsPlainText -Force;

PS C:\> .\ThresholdReport <access Id> -AccessKey $accesskey -AccountName <account name>...'
```
